apiVersion: v1
kind: ConfigMap
metadata:
  name: example-python-script
data:
  10-print-version.py: |
    import sys
    print('Hello! I am 10-print-version.py: Running Python version:')
    print(sys.version)
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: example-cronjob-aio
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: k8s-python-executor
            image: jakemalley/k8s-python-executor:latest
            env:
            - name: ENABLE
              value: "TRUE"
            volumeMounts:
              - mountPath: /opt/scripts
                name: example-scripts
          volumes:
            - name: example-scripts
              configMap:
                name: example-python-script
                defaultMode: 0744
